# Settings that are applied to the templates. This file should be copied to
# the base folder of the play and renamed settings.yml, then modified to suit
# your needs.

---
# Hostname is important as we need to delete an anonymous MySQL
# user that is created with this name, make sure you match this
# up with the output of the command 'hostname' on the server.
machine_hostname: 'linjun12b.dmclub.net'
machine_fqdn: 'linjun12b.dmclub.net'

# This value is used for Apache perfomance tuning
server_ram_gb: 8

timezone: Europe/London

# Ubuntu package mirror - CONSIDER CHANGING THIS IF APT-GET UPDATE FAILS FOR ANY REASON
#package_mirror: ubuntu.mirrors.uk2.net
package_mirror: mirrors.linode.com

# Firewall
security_ufw_state: enabled
security_ufw_ports:
  - { rule: allow, port: 21,    proto: tcp }   # FTP
  - { rule: allow, port: 22,    proto: tcp }   # SSH
  - { rule: allow, port: 80,    proto: tcp }   # HTTP
  - { rule: allow, port: 443,   proto: tcp }   # HTTPS
  - { rule: allow, port: 139,   proto: tcp }   # Samba
  - { rule: allow, port: 445,   proto: tcp }   # Samba
  - { rule: allow, port: 2200,  proto: tcp }   # Vagrant port forwarding
  - { rule: allow, port: 3306,  proto: tcp }   # MySQL
  - { rule: allow, port: 6082,  proto: tcp }   # Varnish admin
  - { rule: allow, port: 8080,  proto: tcp }   # Varnish test port
  - { rule: allow, port: 8983,  proto: tcp }   # Solr-Undertow
  - { rule: allow, port: 11371, proto: tcp }   # HKP - necessary for connecting to GnuPG keyservers when installing signed packages

# Nagios: IP(s) of central monitoring server(s) (comma-delimited if more than one)
nagios_server_ip: '176.58.119.15'

# Apt cache
apt_cache_location: 'http://linode-hub.apewave.com' # Must include protocol e.g. http://
apt_cache_valid_time: 86400

# Apache
apache_server_admin: 'webmaster@linjun12b.dmclub.net'
apache_server_alias: '*.*.linjun12b.dmclub.net'

# Apache performance tuning
apache_max_request_memory_usage_mb: 16

# MySQL configuration
mysql_max_allowed_packet: '128M'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'
innodb_file_per_table: 'innodb_file_per_table'

# MySQL users
mysql_root_password:    'smokinghotsql'
mysql_remote_user:      'remote'
mysql_remote_password:  'Romer8'

# php.ini
php_memory_limit:       '128M'
php_max_execution_time: '30'
php_date_timezone:      'Europe/London'

# vsftp
vsftpd_service_enabled: yes
vsftpd_service_state: started
vsftpd_config: {
    local_enable: 'YES',
    write_enable: 'YES',
    chroot_list_enable: 'YES',
    seccomp_sandbox: 'NO',
    allow_writable_chroot: 'YES'  
}
vsftpd_users:
   - username: ftpuser
     name: FTP User
     password: 'test'

# Samba
workgroup: WORKGROUP
public_share_name: public
public_share_path: /samba/public
private_share_name: private
private_share_path: /samba/private
samba_group_name: smbgrp
smaba_users:
    - { name: 'arbab', smbpasswd: 'pass123' }
    - { name: 'hussain', smbpasswd: 'password' }
  
# Ruby versions
rvm1_gpg_key_server: 'hkp://pgp.mit.edu' # keys.gnupg.net has been down a lot lately
rvm1_rubies:
    - 'ruby-2.2.3'
    
rvm1_default_ruby_version: 'ruby-2.2.3'

# Node
nodejs_version: 4.0

# Mongo
# The chunksize for shards in MB
mongos_chunk_size: 1
# The port in which mongos server should listen on
mongos_port: 8888
# The port for mongo config server
mongoc_port: 7777
# The directory prefix where the database files would be stored
mongodb_datadir_prefix: /data/
# The interface where the mongodb process should listen on.
# Defaults to the first interface. Change this to:
#
# iface: eth1
#
# ...to override.
#
iface: '{{ ansible_default_ipv4.interface }}'
# The password for admin user
mongo_admin_pass: 123456

# Redis
redis_bind: 127.0.0.1

# Varnish
varnish_default_backend_port: "80"
varnish_listen_port: "8080"

