---

- name: Make sure Ansible local facts directory exists
  file:
    dest: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Configure Postfix local facts
  template:
    src: 'etc/ansible/facts.d/postfix.fact.j2'
    dest: '/etc/ansible/facts.d/postfix.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: postfix_register_local_facts

- name: Re-read local facts if they have been modified
  action: setup
  when: postfix_register_local_facts.changed

- include: install_divert.yml
  when: postfix

- include: configure.yml
  when: postfix

- include: disable_revert.yml
  when: not postfix

