---
##
# Java 8, Undertow and Solr
#
- name: Ensure Java 8 is present
  apt_repository: repo='ppa:webupd8team/java'
- name: Auto accept oracle jdk license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
- apt: name=oracle-java8-installer state=present
- apt: name=oracle-java8-set-default state=present

- name: Download Solr-Undertow
  get_url: url=https://github.com/bremeld/solr-undertow/releases/download/v1.1.0/solr-undertow-1.1.0-with-solr-4.10.2.tgz dest=/root

- name: Unarchive Solr-Undertow
  unarchive: src=/root/solr-undertow-1.1.0-with-solr-4.10.2.tgz dest=/root copy=no