---

- name: Install PKI packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_flattened:
    - [ 'ssl-cert', 'make', 'ca-certificates', 'gnutls-bin',
         'openssl', 'openssl-blacklist', 'acl' ]
    - pki_packages

- name: Create base PKI directory
  file:
    path: '{{ pki_base_path }}'
    state: 'directory'
    owner: '{{ pki_owner }}'
    group: '{{ pki_public_group }}'
    mode: '{{ pki_public_dir_mode }}'
  when: pki is defined and pki

- name: Create private groups if requested
  group:
    name: '{{ item }}'
    system: 'true'
    state: 'present'
  with_items: pki_private_groups_present
  when: ((pki is defined and pki) and pki_private_groups_present)

- name: Check if snapshot file exists on Ansible Controller
  stat:
    path: '{{ pki_base_src + "/snapshots/" + ansible_fqdn + "/" + pki_snapshot_file }}'
  register: pki_register_snapshot
  sudo: False
  delegate_to: 'localhost'
  when: pki is defined and pki

- name: Restore PKI from snapshot
  unarchive:
    src: '{{ pki_base_src + "/snapshots/" + ansible_fqdn + "/" + pki_snapshot_file }}/'
    dest: '{{ pki_base_path }}'
  when: ((pki is defined and pki) and (pki_snapshot is defined and pki_snapshot) and
         (ansible_local is undefined or (ansible_local is defined and ansible_local.pki is undefined)) and
         (pki_register_snapshot is defined and pki_register_snapshot.stat.exists))

- include: manage_pki_realms.yml
  when: ((pki is defined and pki) and (ansible_domain is defined and ansible_domain))

- include: manage_pki_authorities.yml
  when: ((pki is defined and pki) and (ansible_domain is defined and ansible_domain))

- include: manage_pki_certificates.yml
  when: ((pki is defined and pki) and (ansible_domain is defined and ansible_domain))

- name: Upload PKI snapshot to Ansible Controller
  fetch:
    src: '{{ pki_snapshot_path + "/" + pki_snapshot_file }}'
    dest: '{{ pki_base_src + "/snapshots/" + ansible_fqdn + "/" + pki_snapshot_file }}'
    flat: True
  register: pki_register_snapshot
  notify: [ 'Regenerate ca-certificates.crt' ]
  when: pki is defined and pki and pki_snapshot is defined and pki_snapshot

- name: Make sure that Ansile local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save local facts
  template:
    src: 'etc/ansible/facts.d/pki.fact.j2'
    dest: '/etc/ansible/facts.d/pki.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: pki_register_facts
  notify: [ 'Gather PKI facts' ]

- name: Flush handlers for PKI if needed
  meta: flush_handlers
  when: ((pki_register_snapshot is defined and pki_register_snapshot.changed) or
         (pki_register_facts is defined and pki_register_facts.changed))

