# Settings that are applied to the templates. This file should be copied to
# the base folder of the play and renamed settings.yml, then modified to suit
# your needs.

---
# Hostname is important as we need to delete an anonymous MySQL
# user that is created with this name, make sure you match this
# up with the output of the command 'hostname' on the server.
machine_hostname: 'scratchpad'
machine_fqdn: 'scratchpad.apewave.com'

# apache
apache_server_admin: 'webmaster@scratchpad.apewave.com'
apache_server_alias: '*.*.scratchpad.apewave.com'

# my.cnf
mysql_max_allowed_packet: '128M'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'
innodb_file_per_table: 'innodb_file_per_table'

# mysql
mysql_root_password:    'smokinghotsql'
mysql_remote_user:      'remote'
mysql_remote_password:  'Romer8'

# php.ini
php_max_execution_time: '90'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_html_errors: 'On'
php_post_max_size: '32M'
php_upload_max_filesize: '32M'
php_date_timezone: 'US/Central'

# vsftpd
#vsftpd_anonymous_enable: 'NO'
#vsftpd_local_enable: 'YES'
#vsftpd_write_enable: 'YES'
#vsftpd_local_umask: '002'

vsftpd_service_enabled: yes
vsftpd_service_state: started
vsftpd_users:
   - username: ftpuser
     name: FTP User
     password: 'test'
