# ----------------------------------------------------------------------------------------
# Debian Build Settings
# ----------------------------------------------------------------------------------------
# Settings that are applied during the build.

---

machine_hostname: 'hzhaug16a.dmclub.net'
machine_fqdn: 'hzhaug16a.dmclub.net'

# This value is used for perfomance tuning (Apache, MySQL, etc)
server_ram_gb: 2

timezone: Etc/UTC

# Debian package mirror - CONSIDER CHANGING THIS IF APT-GET UPDATE FAILS FOR ANY REASON
package_mirror: mirrors.linode.com

# Firewall
security_ufw_state: enabled
security_ufw_ports:
  - { rule: allow, port: 21,    proto: tcp }   # FTP
  - { rule: allow, port: 22,    proto: tcp }   # SSH
  - { rule: allow, port: 80,    proto: tcp }   # HTTP
  - { rule: allow, port: 443,   proto: tcp }   # HTTPS
  - { rule: allow, port: 139,   proto: tcp }   # Samba
  - { rule: allow, port: 445,   proto: tcp }   # Samba
  - { rule: allow, port: 2200,  proto: tcp }   # Vagrant port forwarding
  - { rule: allow, port: 3306,  proto: tcp }   # MySQL
  - { rule: allow, port: 11371, proto: tcp }   # HKP - necessary for connecting to GnuPG keyservers when installing signed packages

# Apt cache
#apt_cache_location: 'http://linode-hub.apewave.com' # Must include protocol e.g. http://
#apt_cache_valid_time: 86400

# Sensu client
# Sensu client variable
sensu_client_hostname:           "{{ ansible_hostname }}"
sensu_client_address:            "localhost"
sensu_client_subscription_names: [production]

# Sensu server (remote)
sensu_server_rabbitmq_vhost:    "/sensu"
sensu_server_rabbitmq_hostname: "139.162.221.82"
sensu_server_rabbitmq_port:     "5672"
sensu_server_rabbitmq_insecure: true
sensu_server_rabbitmq_user:     "sensu"
sensu_server_rabbitmq_password: "boomerang12_"
