# Settings that are applied to the templates. This file should be copied to
# the base folder of the play and renamed settings.yml, then modified to suit
# your needs.

---
# Hostname is important as we need to delete an anonymous MySQL
# user that is created with this name, make sure you match this
# up with the output of the command 'hostname' on the server.
machine_hostname: 'scratchpad'
machine_fqdn: 'scratchpad.apewave.com'

timezone: Europe/London

# Firewall
security_ufw_state: enabled
security_ufw_ports:
  - { rule: allow, port: 21,   proto: tcp }   # FTP
  - { rule: allow, port: 22,   proto: tcp }   # SSH
  - { rule: allow, port: 80,   proto: tcp }   # HTTP
  - { rule: allow, port: 139,  proto: tcp }   # Samba
  - { rule: allow, port: 445,  proto: tcp }   # Samba
  - { rule: allow, port: 2200, proto: tcp }   # Vagrant Port Forwarding
  - { rule: allow, port: 3306, proto: tcp }   # MySQL

# Nagios: IP(s) of central monitoring server(s) (comma-delimited if more than one)
nagios_server_ip: '176.58.119.15'

# Apache
apache_server_admin: 'webmaster@scratchpad.apewave.com'
apache_server_alias: '*.*.scratchpad.apewave.com'

# MySQL configuration
mysql_max_allowed_packet: '128M'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'
innodb_file_per_table: 'innodb_file_per_table'

# MySQL users
mysql_root_password:    'smokinghotsql'
mysql_remote_user:      'remote'
mysql_remote_password:  'Romer8'

# php.ini
php_memory_limit:       '128M'
php_max_execution_time: '30'
php_date_timezone:      'Europe/London'

# vsftpd
#vsftpd_anonymous_enable: 'NO'
#vsftpd_local_enable: 'YES'
#vsftpd_write_enable: 'YES'
#vsftpd_local_umask: '002'

vsftpd_service_enabled: yes
vsftpd_service_state: started
vsftpd_users:
   - username: ftpuser
     name: FTP User
     password: 'test'

# Ruby versions
rvm1_rubies:
    - 'ruby-2.2.0'
    
rvm1_default_ruby_version: 'ruby-2.2.0'
