---
- hosts: all
  sudo: true
  vars_files:
    - config.yml
  
  roles: 

  # ------------------------------------------------------------
  # Utilities, system administration, diagnostics and monitoring
  - common 
  - sensu
  #- webmin

  # -------------------------------------------
  # LAMP stack, with all our bells-and-whistles
  #- apache 
  #- mysql 
  #- php 

  # ----------------
  # WebApp CLI tools
  #- drush
  #- wp-cli
  
  # VSFTP
  #- franklinkim.vsftpd
  
  # -----------------------------------
  # Postfix, configured as null client
  # A null client is a machine that can only send mail. It receives no mail from the network, and it does not deliver any mail locally. 
  #- postfix
  
  # ----------------------------------------------------------------
  # Python ecosystem tools: Pip, VirtualEnv, VirtualEnvWrapper, LXML
  #- python-extras
  
  # ---------------------------------------------------------------------------------------
  # Ruby Version Manager and Ruby (see config.yml for the Ruby versions that get installed)
  #- rvm_io.rvm1-ruby
  
  # -------------------------------------------------------
  # Sass, Compass, and various other CSS-preprocessor tools
  #- sass-tools
  
  # ----
  # Node
  #- nodejs

  # -----------------------------
  # Yeoman, Bower, Grunt and Gulp
  #- node-build-tools
  
  # -----
  # Mongo
  # - mongo
  #- php5-mongo 
  
  # -------------------------------
  # Apache Solr running on Undertow
  #- solr-undertow

  # -----
  # Redis
  #- DavidWittman.redis  
  
  # --------------------------------
  # Varnish - cacheing reverse proxy
  #- varnish
  
  # Add: DNSMAsq, Samba, Squid?, Vagrant, Docker

  # ---------------------------------------------------------------------
  # Set up the Firewall (see config.yml for list of rules to apply)
  #
  # It's safest to do this last if server if behind a proxy (e.g. Host Virtual)
  # otherwise running a Firewall can cause issues with apt-get update and software installation in general
  #
  # Can be done first on Linode and Hetzner (which is preferred) 
  - secure-server

