---
- hosts: all
  sudo: true
  vars_files:
    - config.yml
  
  roles: 

  # First set up the Firewall
  - nickjj.security

  # Utilities, system administration and diagnostics
  - common 
  - webmin
  - nagios-client

  # LAMP stack, with all our bells-and-whistles
  - apache 
  - mysql 
  - php 

  # WebApp CLI tools
  - drush
  - wp-cli
  
  # VSFTP
  
  # Postfix, configured as - WARNING TRASHES FIREWALL!
  # - { role: debops.postfix, postfix: ['network', 'mx', 'submission'], ansible_fqdn: '{{ machine_fqdn }}', ansible_hostname: '{{ machine_hostname }}' }
  
  # Python ecosystem tools: Pip, VirtualEnv, VirtualEnvWrapper, LXML
  - python-extras
  
  # Ruby Version Manager and Ruby (see config.yml for the Ruby versions that get installed)
  - rvm_io.rvm1-ruby
  
  # Sass, Compass, and various other CSS-preprocessor tools
  - sass-tools
  
  # Node
  - nodejs

  # Yeoman, Bower, Grunt and Gulp
  - node-build-tools
  
  # Mongo
  - mongo
  - php5-mongo 
  
  # Apache Solr running on Undertow
  - solr-undertow

  # Redis
  
  # Varnish
  
  # Add: NRPE, DNSMAsq, Squid, Vagrant, Docker

