---
- hosts: all
  sudo: true
  vars_files:
    - config.yml
  
  roles: 

  # ---------------------------------------------------------------------
  # First set up the Firewall (see config.yml for list of rules to apply)
  - secure-server

  # ------------------------------------------------
  # Utilities, system administration and diagnostics
  - common 
  - webmin
  - nagios-client

  # -------------------------------------------
  # LAMP stack, with all our bells-and-whistles
  - apache 
  - mysql 
  - php 

  # ----------------
  # WebApp CLI tools
  - drush
  - wp-cli
  
  # VSFTP
  - franklinkim.vsftpd
  
  # -----------------------------------
  # Postfix, configured as null client
  # A null client is a machine that can only send mail. It receives no mail from the network, and it does not deliver any mail locally. 
  - postfix
  
  # ----------------------------------------------------------------
  # Python ecosystem tools: Pip, VirtualEnv, VirtualEnvWrapper, LXML
  - python-extras
  
  # ---------------------------------------------------------------------------------------
  # Ruby Version Manager and Ruby (see config.yml for the Ruby versions that get installed)
  - rvm_io.rvm1-ruby
  
  # -------------------------------------------------------
  # Sass, Compass, and various other CSS-preprocessor tools
  - sass-tools
  
  # ----
  # Node
  - nodejs

  # -----------------------------
  # Yeoman, Bower, Grunt and Gulp
  - node-build-tools
  
  # -----
  # Mongo
  # - mongo
  - php5-mongo 
  
  # -------------------------------
  # Apache Solr running on Undertow
  - solr-undertow

  # -----
  # Redis
  - DavidWittman.redis  
  
  # --------------------------------
  # Varnish - cacheing reverse proxy
  - varnish
  
  # Add: DNSMAsq, Samba, Squid?, Vagrant, Docker

