---
- hosts: all
  sudo: true
  vars_files:
    - config.yml
  
  roles: 

  # Utilities, system administration and diagnostics
  - common 
  - webmin

  # LAMP stack, with all our bells-and-whistles
  - apache 
  - mysql 
  - php 

  # Mongo
  #- mongo 
  
  tasks:
    
    ##
    # Restart services
    #
    - name: Restart Apache
      action: service name=apache2 state=restarted
      tags: common

    - name: Restart MySQL
      action: service name=mysql state=restarted
      tags: common

    - name: Restart vsftpd
      action: service name=vsftpd state=restarted
      tags: ftp
