---
##
# ex_install, setuptools, pip and virtualenv and virtualenvwrapper
#
- name: Ensure dev packages are present, inc. python-dev 
  apt: name={{ item }} state=present
  with_items:
    - libpq-dev
    - python-dev
    - libjpeg-dev
    - libpng-dev
  
- name: Copy ez_setup.py to server
  copy: src=ez_setup.py dest=/usr/local/src/ez_setup.py

- name: Run ez_setup.py
  command: 'python /usr/local/src/ez_setup.py'
  
- name: Ensure pip is present
  apt: name=python-pip state=latest

- name: Ensure virtualenv is present
  pip: name=virtualenv state=latest
  
- name: Ensure virtualenvwrapper is present
  pip: name=virtualenvwrapper state=latest

# Add LXML
# These need to be installed first to avoid compilation errors:
- name: LXML | Ensure libxml2-dev libxslt-dev lib32z1-dev are present
  apt: name={{ item }} state=present
  with_items:
    - libxml2-dev
    - libxslt-dev
    - lib32z1-dev

- name: LXML | Ensure LXML is present
  pip: name=lxml state=latest
