---
# tasks file for common
 
##
# Set hostname
#
- name: Set hostname
  hostname: name={{ machine_hostname }}
- lineinfile: dest=/etc/hosts line='127.0.0.1 {{ machine_hostname }}'

##
# Ensure permissions are correctly set up on home directory (otherwise ssh publickey access fails)
#
- name: Ensure permissions are correctly set up on home directory
  file: path=/root state=touch mode='g-w'
- name: Ensure permissions are correctly set up on .ssh
  file: path=/root/.ssh state=touch mode=0700
- name: Ensure permissions are correctly set up on .ssh/authorized_keys
  file: path=/root/.ssh/authorized_keys state=touch mode=0600

##
# Set timezone
#
- name: Set server timezone
  command: export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
  command: echo '{{ timezone }}' > /etc/timezone'
  command: dpkg-reconfigure -f noninteractive tzdata

##
# Add user www and group www
#
- name: Add user www and group www
  group: name=www state=present
- user: name=www comment="Webserver user" group=www
  
##
# Set apt-cache location
#
- name: Set apt-cache location (server where we have apt-cache-ng installed)
  template: src=etc-apt-apt.conf.d-02proxy.j2 dest=/etc/apt/apt.conf.d/02Proxy owner=root group=root mode=0644

##
# Update package list
#
- name: Ensure Hetzner's crawlingly slow mirrors are NOT consulted
  lineinfile: dest=/etc/apt/sources.list state=absent regexp="mirror.hetzner.de"
- name: Update apt cache
  apt: update_cache=yes upgrade=yes
  # apt: update_cache=yes cache_valid_time={{ apt_cache_valid_time }} upgrade=yes

##
# Start installing
#
- name: Install various common packages
  action: apt pkg={{ item }} state=latest
  tags: common
  with_items:
    - expect
    - zip
    - unzip
    - curl
    - telnet
    - mailutils
    - samba
    - smbclient
    - subversion
    - git-core
    - git-svn
    - gcc
    - g++
    - autoconf
    - automake
    - build-essential
    - libtool
    - ncurses-dev
    - libjpeg-dev
    - make
    - libmyodbc 
    - debconf-utils
    - traceroute
    - ftp
    - ncftp
    - goaccess
    - htop
        
