---
# tasks file for webmin

##
# Webmin
#
- name: Install Webmin | Add Webmin repository
  lineinfile: dest=/etc/apt/sources.list line='deb http://download.webmin.com/download/repository sarge contrib'

- name: Install Webmin | Add new repo key
  apt_key: url=http://www.webmin.com/jcameron-key.asc state=present

- name: Install Webmin | Update apt cache
  apt: update_cache=yes

- name: Install Webmin | Install Webmin
  apt: name=webmin state=prese
 