---
galaxy_info:
  author: Nick Janetakis
  description: Install the latest stable version of nodejs.
  company: 
  license: license (MIT)
  min_ansible_version: 1.5

  platforms:
  - name: Ubuntu
    versions:
    - all

  categories:
  - development
  - web

dependencies: []