---
# tasks file for php

- name: Install php
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-dev
    - php5-gd
    - php5-mcrypt

- name: Customise apache2/php.ini
  template: src=apache2-php.ini.j2 dest=/etc/php5/apache2/php.ini mode=0644