---
# tasks file for apache

- name: Install supporting libs
  apt: name={{ item }} state=present
  with_items:
    - libexpat1
    - ssl-cert 

- name: Install Apache
  apt: name=apache2 state=present

# Disable mpm_event (as we're using mpm-itk instead, and it causes conflicts unless you do this)
- name: Disable mpm_event 
  apache2_module: state=absent name=mpm_event

- name: Install Apache modules
  apt: name={{ item }} state=present
  with_items:
    - libapache2-mod-wsgi
    - libapache2-mpm-itk
    - apache2-utils
    #-apache2-mpm-itk
  
- name: Enable mod_rewrite and mod_headers
  apache2_module: name={{ item }} state=present 
  with_items:
    - headers
    - rewrite

- name: Set up default configuration for affiliate mode
  template: src=apache2.conf.j2 dest=/etc/apache2/apache2.conf
  notify: restart apache

- name: Create directories for default site
  file: path=/home/sites/_default/{{ item }} state=directory owner=www group=www mode=0775
  with_items:
    - bin
    - cgi-bin
    - logs
    - temp
    - www

- name: Install default site
  template: src=index.html.j2 dest=/home/sites/_default/www/index.html owner=www group=www mode=0775

- name: Install PHP info
  copy: src=info.php dest=/home/sites/_default/www/info.php owner=www group=www mode=0775

