---
#- name: Install NVM
#  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash

- name: Add NVM to path
  shell: . /root/.bashrc

- name: Install latest stable Node
  shell: nvm install stable

- name: Set the default
  shell: nvm alias default stable

- name: Use the latest stable Node
  shell: nvm use default

#- name: Get the corresponding version of npm - no longer needed as npm comes with node these days
# shell: curl https://npmjs.org/install.sh | sh
